# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import inventory_system_pb2 as inventory__system__pb2


class InventorySystemStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetProduct = channel.unary_unary(
        '/InventorySystem/GetProduct',
        request_serializer=inventory__system__pb2.ProductIdentifier.SerializeToString,
        response_deserializer=inventory__system__pb2.Product.FromString,
        )
    self.AddProduct = channel.unary_unary(
        '/InventorySystem/AddProduct',
        request_serializer=inventory__system__pb2.Product.SerializeToString,
        response_deserializer=inventory__system__pb2.Success.FromString,
        )
    self.GetProductsByManufacturer = channel.unary_stream(
        '/InventorySystem/GetProductsByManufacturer',
        request_serializer=inventory__system__pb2.Manufacturer.SerializeToString,
        response_deserializer=inventory__system__pb2.Product.FromString,
        )
    self.GetProductsInStock = channel.unary_stream(
        '/InventorySystem/GetProductsInStock',
        request_serializer=inventory__system__pb2.Empty.SerializeToString,
        response_deserializer=inventory__system__pb2.Product.FromString,
        )
    self.UpdateProduct = channel.unary_unary(
        '/InventorySystem/UpdateProduct',
        request_serializer=inventory__system__pb2.Product.SerializeToString,
        response_deserializer=inventory__system__pb2.Success.FromString,
        )


class InventorySystemServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetProduct(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddProduct(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetProductsByManufacturer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetProductsInStock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateProduct(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InventorySystemServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetProduct': grpc.unary_unary_rpc_method_handler(
          servicer.GetProduct,
          request_deserializer=inventory__system__pb2.ProductIdentifier.FromString,
          response_serializer=inventory__system__pb2.Product.SerializeToString,
      ),
      'AddProduct': grpc.unary_unary_rpc_method_handler(
          servicer.AddProduct,
          request_deserializer=inventory__system__pb2.Product.FromString,
          response_serializer=inventory__system__pb2.Success.SerializeToString,
      ),
      'GetProductsByManufacturer': grpc.unary_stream_rpc_method_handler(
          servicer.GetProductsByManufacturer,
          request_deserializer=inventory__system__pb2.Manufacturer.FromString,
          response_serializer=inventory__system__pb2.Product.SerializeToString,
      ),
      'GetProductsInStock': grpc.unary_stream_rpc_method_handler(
          servicer.GetProductsInStock,
          request_deserializer=inventory__system__pb2.Empty.FromString,
          response_serializer=inventory__system__pb2.Product.SerializeToString,
      ),
      'UpdateProduct': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateProduct,
          request_deserializer=inventory__system__pb2.Product.FromString,
          response_serializer=inventory__system__pb2.Success.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'InventorySystem', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
