# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import inventory_system_pb2 as inventory__system__pb2


class InventorySystemStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetProduct = channel.unary_unary(
        '/InventorySystem/GetProduct',
        request_serializer=inventory__system__pb2.ProductIdentifier.SerializeToString,
        response_deserializer=inventory__system__pb2.Product.FromString,
        )
    self.AddProduct = channel.unary_unary(
        '/InventorySystem/AddProduct',
        request_serializer=inventory__system__pb2.Product.SerializeToString,
        response_deserializer=inventory__system__pb2.ProductIdentifier.FromString,
        )
    self.GetProductsByManufacturer = channel.unary_stream(
        '/InventorySystem/GetProductsByManufacturer',
        request_serializer=inventory__system__pb2.Manufacturer.SerializeToString,
        response_deserializer=inventory__system__pb2.Product.FromString,
        )
    self.GetProductsInStock = channel.unary_stream(
        '/InventorySystem/GetProductsInStock',
        request_serializer=inventory__system__pb2.Empty.SerializeToString,
        response_deserializer=inventory__system__pb2.Product.FromString,
        )
    self.DecreaseProductAmount = channel.unary_unary(
        '/InventorySystem/DecreaseProductAmount',
        request_serializer=inventory__system__pb2.ProductAmount.SerializeToString,
        response_deserializer=inventory__system__pb2.Success.FromString,
        )
    self.IncreaseProductAmount = channel.unary_unary(
        '/InventorySystem/IncreaseProductAmount',
        request_serializer=inventory__system__pb2.ProductAmount.SerializeToString,
        response_deserializer=inventory__system__pb2.Success.FromString,
        )
    self.UpdateProductManufacturer = channel.unary_unary(
        '/InventorySystem/UpdateProductManufacturer',
        request_serializer=inventory__system__pb2.ProductManufacturer.SerializeToString,
        response_deserializer=inventory__system__pb2.Success.FromString,
        )
    self.UpdateProductDescription = channel.unary_unary(
        '/InventorySystem/UpdateProductDescription',
        request_serializer=inventory__system__pb2.ProductDescription.SerializeToString,
        response_deserializer=inventory__system__pb2.Success.FromString,
        )
    self.UpdateProductSaleCost = channel.unary_unary(
        '/InventorySystem/UpdateProductSaleCost',
        request_serializer=inventory__system__pb2.ProductSaleCost.SerializeToString,
        response_deserializer=inventory__system__pb2.Success.FromString,
        )
    self.UpdateProductWholesaleCost = channel.unary_unary(
        '/InventorySystem/UpdateProductWholesaleCost',
        request_serializer=inventory__system__pb2.ProductWholesaleCost.SerializeToString,
        response_deserializer=inventory__system__pb2.Success.FromString,
        )
    self.GetOrder = channel.unary_unary(
        '/InventorySystem/GetOrder',
        request_serializer=inventory__system__pb2.OrderID.SerializeToString,
        response_deserializer=inventory__system__pb2.Order.FromString,
        )
    self.AddOrder = channel.unary_unary(
        '/InventorySystem/AddOrder',
        request_serializer=inventory__system__pb2.Order.SerializeToString,
        response_deserializer=inventory__system__pb2.OrderID.FromString,
        )
    self.AddProductToOrder = channel.unary_unary(
        '/InventorySystem/AddProductToOrder',
        request_serializer=inventory__system__pb2.OrderProduct.SerializeToString,
        response_deserializer=inventory__system__pb2.Success.FromString,
        )
    self.RemoveProductFromOrder = channel.unary_unary(
        '/InventorySystem/RemoveProductFromOrder',
        request_serializer=inventory__system__pb2.OrderProduct.SerializeToString,
        response_deserializer=inventory__system__pb2.Success.FromString,
        )
    self.UpdateOrderDestination = channel.unary_unary(
        '/InventorySystem/UpdateOrderDestination',
        request_serializer=inventory__system__pb2.OrderDestination.SerializeToString,
        response_deserializer=inventory__system__pb2.Success.FromString,
        )
    self.UpdateOrderDate = channel.unary_unary(
        '/InventorySystem/UpdateOrderDate',
        request_serializer=inventory__system__pb2.OrderDate.SerializeToString,
        response_deserializer=inventory__system__pb2.Success.FromString,
        )
    self.UpdateOrderPaid = channel.unary_unary(
        '/InventorySystem/UpdateOrderPaid',
        request_serializer=inventory__system__pb2.OrderPaid.SerializeToString,
        response_deserializer=inventory__system__pb2.Success.FromString,
        )
    self.UpdateOrderShipped = channel.unary_unary(
        '/InventorySystem/UpdateOrderShipped',
        request_serializer=inventory__system__pb2.OrderShipped.SerializeToString,
        response_deserializer=inventory__system__pb2.Success.FromString,
        )
    self.GetUnshippedOrders = channel.unary_stream(
        '/InventorySystem/GetUnshippedOrders',
        request_serializer=inventory__system__pb2.Empty.SerializeToString,
        response_deserializer=inventory__system__pb2.Order.FromString,
        )
    self.GetUnpaidOrders = channel.unary_stream(
        '/InventorySystem/GetUnpaidOrders',
        request_serializer=inventory__system__pb2.Empty.SerializeToString,
        response_deserializer=inventory__system__pb2.Order.FromString,
        )


class InventorySystemServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetProduct(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddProduct(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetProductsByManufacturer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetProductsInStock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DecreaseProductAmount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IncreaseProductAmount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateProductManufacturer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateProductDescription(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateProductSaleCost(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateProductWholesaleCost(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddProductToOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveProductFromOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateOrderDestination(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateOrderDate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateOrderPaid(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateOrderShipped(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUnshippedOrders(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUnpaidOrders(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InventorySystemServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetProduct': grpc.unary_unary_rpc_method_handler(
          servicer.GetProduct,
          request_deserializer=inventory__system__pb2.ProductIdentifier.FromString,
          response_serializer=inventory__system__pb2.Product.SerializeToString,
      ),
      'AddProduct': grpc.unary_unary_rpc_method_handler(
          servicer.AddProduct,
          request_deserializer=inventory__system__pb2.Product.FromString,
          response_serializer=inventory__system__pb2.ProductIdentifier.SerializeToString,
      ),
      'GetProductsByManufacturer': grpc.unary_stream_rpc_method_handler(
          servicer.GetProductsByManufacturer,
          request_deserializer=inventory__system__pb2.Manufacturer.FromString,
          response_serializer=inventory__system__pb2.Product.SerializeToString,
      ),
      'GetProductsInStock': grpc.unary_stream_rpc_method_handler(
          servicer.GetProductsInStock,
          request_deserializer=inventory__system__pb2.Empty.FromString,
          response_serializer=inventory__system__pb2.Product.SerializeToString,
      ),
      'DecreaseProductAmount': grpc.unary_unary_rpc_method_handler(
          servicer.DecreaseProductAmount,
          request_deserializer=inventory__system__pb2.ProductAmount.FromString,
          response_serializer=inventory__system__pb2.Success.SerializeToString,
      ),
      'IncreaseProductAmount': grpc.unary_unary_rpc_method_handler(
          servicer.IncreaseProductAmount,
          request_deserializer=inventory__system__pb2.ProductAmount.FromString,
          response_serializer=inventory__system__pb2.Success.SerializeToString,
      ),
      'UpdateProductManufacturer': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateProductManufacturer,
          request_deserializer=inventory__system__pb2.ProductManufacturer.FromString,
          response_serializer=inventory__system__pb2.Success.SerializeToString,
      ),
      'UpdateProductDescription': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateProductDescription,
          request_deserializer=inventory__system__pb2.ProductDescription.FromString,
          response_serializer=inventory__system__pb2.Success.SerializeToString,
      ),
      'UpdateProductSaleCost': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateProductSaleCost,
          request_deserializer=inventory__system__pb2.ProductSaleCost.FromString,
          response_serializer=inventory__system__pb2.Success.SerializeToString,
      ),
      'UpdateProductWholesaleCost': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateProductWholesaleCost,
          request_deserializer=inventory__system__pb2.ProductWholesaleCost.FromString,
          response_serializer=inventory__system__pb2.Success.SerializeToString,
      ),
      'GetOrder': grpc.unary_unary_rpc_method_handler(
          servicer.GetOrder,
          request_deserializer=inventory__system__pb2.OrderID.FromString,
          response_serializer=inventory__system__pb2.Order.SerializeToString,
      ),
      'AddOrder': grpc.unary_unary_rpc_method_handler(
          servicer.AddOrder,
          request_deserializer=inventory__system__pb2.Order.FromString,
          response_serializer=inventory__system__pb2.OrderID.SerializeToString,
      ),
      'AddProductToOrder': grpc.unary_unary_rpc_method_handler(
          servicer.AddProductToOrder,
          request_deserializer=inventory__system__pb2.OrderProduct.FromString,
          response_serializer=inventory__system__pb2.Success.SerializeToString,
      ),
      'RemoveProductFromOrder': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveProductFromOrder,
          request_deserializer=inventory__system__pb2.OrderProduct.FromString,
          response_serializer=inventory__system__pb2.Success.SerializeToString,
      ),
      'UpdateOrderDestination': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateOrderDestination,
          request_deserializer=inventory__system__pb2.OrderDestination.FromString,
          response_serializer=inventory__system__pb2.Success.SerializeToString,
      ),
      'UpdateOrderDate': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateOrderDate,
          request_deserializer=inventory__system__pb2.OrderDate.FromString,
          response_serializer=inventory__system__pb2.Success.SerializeToString,
      ),
      'UpdateOrderPaid': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateOrderPaid,
          request_deserializer=inventory__system__pb2.OrderPaid.FromString,
          response_serializer=inventory__system__pb2.Success.SerializeToString,
      ),
      'UpdateOrderShipped': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateOrderShipped,
          request_deserializer=inventory__system__pb2.OrderShipped.FromString,
          response_serializer=inventory__system__pb2.Success.SerializeToString,
      ),
      'GetUnshippedOrders': grpc.unary_stream_rpc_method_handler(
          servicer.GetUnshippedOrders,
          request_deserializer=inventory__system__pb2.Empty.FromString,
          response_serializer=inventory__system__pb2.Order.SerializeToString,
      ),
      'GetUnpaidOrders': grpc.unary_stream_rpc_method_handler(
          servicer.GetUnpaidOrders,
          request_deserializer=inventory__system__pb2.Empty.FromString,
          response_serializer=inventory__system__pb2.Order.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'InventorySystem', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
