# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory_system.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inventory_system.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x16inventory_system.proto\"\x07\n\x05\x45mpty\"\x1a\n\x07Success\x12\x0f\n\x07success\x18\x01 \x01(\x08\"-\n\x11ProductIdentifier\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"$\n\x0cManufacturer\x12\x14\n\x0cmanufacturer\x18\x01 \x01(\t\"\x89\x01\n\x07Product\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x14\n\x0cmanufacturer\x18\x05 \x01(\t\x12\x11\n\tsale_cost\x18\x06 \x01(\x01\x12\x16\n\x0ewholesale_cost\x18\x07 \x01(\x01\x32\xf0\x01\n\x0fInventorySystem\x12,\n\nGetProduct\x12\x12.ProductIdentifier\x1a\x08.Product\"\x00\x12\"\n\nAddProduct\x12\x08.Product\x1a\x08.Success\"\x00\x12\x38\n\x19GetProductsByManufacturer\x12\r.Manufacturer\x1a\x08.Product\"\x00\x30\x01\x12*\n\x12GetProductsInStock\x12\x06.Empty\x1a\x08.Product\"\x00\x30\x01\x12%\n\rUpdateProduct\x12\x08.Product\x1a\x08.Success\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=33,
)


_SUCCESS = _descriptor.Descriptor(
  name='Success',
  full_name='Success',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='Success.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=61,
)


_PRODUCTIDENTIFIER = _descriptor.Descriptor(
  name='ProductIdentifier',
  full_name='ProductIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ProductIdentifier.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='ProductIdentifier.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=108,
)


_MANUFACTURER = _descriptor.Descriptor(
  name='Manufacturer',
  full_name='Manufacturer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='manufacturer', full_name='Manufacturer.manufacturer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=146,
)


_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Product.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='Product.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='Product.amount', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='Product.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manufacturer', full_name='Product.manufacturer', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sale_cost', full_name='Product.sale_cost', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wholesale_cost', full_name='Product.wholesale_cost', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=286,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Success'] = _SUCCESS
DESCRIPTOR.message_types_by_name['ProductIdentifier'] = _PRODUCTIDENTIFIER
DESCRIPTOR.message_types_by_name['Manufacturer'] = _MANUFACTURER
DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'inventory_system_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Success = _reflection.GeneratedProtocolMessageType('Success', (_message.Message,), {
  'DESCRIPTOR' : _SUCCESS,
  '__module__' : 'inventory_system_pb2'
  # @@protoc_insertion_point(class_scope:Success)
  })
_sym_db.RegisterMessage(Success)

ProductIdentifier = _reflection.GeneratedProtocolMessageType('ProductIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTIDENTIFIER,
  '__module__' : 'inventory_system_pb2'
  # @@protoc_insertion_point(class_scope:ProductIdentifier)
  })
_sym_db.RegisterMessage(ProductIdentifier)

Manufacturer = _reflection.GeneratedProtocolMessageType('Manufacturer', (_message.Message,), {
  'DESCRIPTOR' : _MANUFACTURER,
  '__module__' : 'inventory_system_pb2'
  # @@protoc_insertion_point(class_scope:Manufacturer)
  })
_sym_db.RegisterMessage(Manufacturer)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'inventory_system_pb2'
  # @@protoc_insertion_point(class_scope:Product)
  })
_sym_db.RegisterMessage(Product)



_INVENTORYSYSTEM = _descriptor.ServiceDescriptor(
  name='InventorySystem',
  full_name='InventorySystem',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=289,
  serialized_end=529,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProduct',
    full_name='InventorySystem.GetProduct',
    index=0,
    containing_service=None,
    input_type=_PRODUCTIDENTIFIER,
    output_type=_PRODUCT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddProduct',
    full_name='InventorySystem.AddProduct',
    index=1,
    containing_service=None,
    input_type=_PRODUCT,
    output_type=_SUCCESS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetProductsByManufacturer',
    full_name='InventorySystem.GetProductsByManufacturer',
    index=2,
    containing_service=None,
    input_type=_MANUFACTURER,
    output_type=_PRODUCT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetProductsInStock',
    full_name='InventorySystem.GetProductsInStock',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_PRODUCT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateProduct',
    full_name='InventorySystem.UpdateProduct',
    index=4,
    containing_service=None,
    input_type=_PRODUCT,
    output_type=_SUCCESS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INVENTORYSYSTEM)

DESCRIPTOR.services_by_name['InventorySystem'] = _INVENTORYSYSTEM

# @@protoc_insertion_point(module_scope)
